// <auto-generated />
using System;
using BTCPayServer.Plugins.B2PCentral;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.B2PCentral.Migrations
{
    [DbContext(typeof(B2PCentralPluginDbContext))]
    partial class B2PCentralPluginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.B2PCentral")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.B2PCentral.Data.B2PData", b =>
                {
                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ApiKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ApiKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ProvidersString")
                        .HasColumnType("text");

                    b.HasKey("B2PSettings");

                    b.ToTable("B2PSettings", "BTCPayServer.Plugins.B2PCentral");
                });
#pragma warning restore 612, 618
        }
    }
}
